#!/usr/bin/env python3
"""
monte_carlo_backtest.py

Orchestrates an advanced Monte Carlo backtesting workflow, designed to feel
like an extension of the deterministic backtester.

Workflow:
1.  Loads historical data and splits it into train/test sets based on user-defined mode.
2.  Runs a standard, deterministic backtest on the actual test data to establish a baseline.
3.  Fits a GARCH(1,1) model to the returns of the training data set (diffusion component).
4.  Estimates jump parameters from GARCH residuals.
5.  Generates synthetic OHLCV data paths incorporating GARCH-modeled diffusion and a Poisson-driven jump process.
6.  Loads a pre-trained ML model for signal generation.
7.  Loops for a specified number of simulations:
    a. Generates a synthetic OHLCV data path with the same length as the test set.
    b. Runs the full feature engineering -> signal generation -> backtesting pipeline.
    c. Stores the summary metrics and the full equity curve from each run.
8.  Aggregates all results and uses a dedicated analyzer to generate and save:
    a. Statistical summary of performance metrics (CSV).
    b. Distribution plots for key metrics (e.g., Total Return).
    c. A comparative plot of simulated equity curves vs. the deterministic baseline.
    d. A risk/reward scatter plot (Return vs. Drawdown).
    e. A sample of simulated OHLCV paths.
9.  Saves all artifacts to a dedicated, non-conflicting subdirectory to keep results safe.

MODIFIED (NEW): Now uses the comprehensive `app_config` object from `config.params`
                for all configuration access.
MODIFIED: Updated argument parsing to retrieve default values from `app_config`.
MODIFIED: Passed specific config dataclass objects (e.g., app_config.strategy)
          directly to the BacktestSimulator constructor.
MODIFIED: Updated the `metric_keys_template` to match the new metric keys
          generated by the BacktestSimulator.
UPDATED: Renamed Backtester to BacktestSimulator to reflect the new class name.
UPDATED: Changed ResultsAnalyser to ResultAnalyser in references.
UPDATED: Corrected model choices to use AVAILABLE_MODEL_TYPES from ModelConfig.
FIXED: Removed incorrect `get_model_config` call; `app_config.model` is directly passed to ModelTrainer.
FIXED: Corrected keyword argument for ModelTrainer initialization from 'config' to 'model_config'.
FIXED: Corrected the preprocessor check to use 'trainer.preprocessor_builder.preprocessor'.
"""

import argparse
import logging
import sys
from pathlib import Path
from typing import Optional, List, Dict, Any
import pandas as pd
import numpy as np
import copy
from tqdm import tqdm
import re # Added for pattern matching in ResultsAnalyser
from datetime import datetime, timezone

# --- IMPORTANT: Set Matplotlib backend BEFORE importing pyplot ---
import matplotlib
matplotlib.use('Agg') # Use the 'Agg' backend for non-interactive plotting
import matplotlib.pyplot as plt
import seaborn as sns

# --- Add Project Root to sys.path ---
try:
    script_dir = Path(__file__).resolve().parent
    PROJECT_ROOT = script_dir.parent
except NameError:
    PROJECT_ROOT = Path('.').resolve()
sys.path.insert(0, str(PROJECT_ROOT))

# --- Import Project Modules ---
try:
    # Import the aggregated application configuration
    from config.params import app_config

    # Import centralized path configurations
    from config.paths import PATHS

    # Import the DataManager
    from utils.data_manager import DataManager
    # Import the ModelTrainer
    from utils.training.model_trainer import ModelTrainer
    # Import the FeaturesEngineer
    from utils.feature_engineering.feature_engineer import FeaturesEngineer
    # Import the BacktestSimulator (renamed from Backtester)
    from utils.backtest_engine.simulator import BacktestSimulator # Updated import path
    # Import the logging setup function
    from utils.logger_config import setup_rotating_logging
    # Import arch for GARCH modeling
    from arch import arch_model
except ImportError as e:
    print(f"ERROR: Failed to import necessary project modules: {e}", file=sys.stderr)
    print("Please ensure all dependencies are installed (including 'tqdm', 'seaborn', 'arch') and paths are correct.", file=sys.stderr)
    sys.exit(1)

# --- Logger Setup ---
setup_rotating_logging("mc_backtest")
logger = logging.getLogger(__name__)


class PricePathSimulator:
    """
    Fits a GARCH model for the diffusion component and generates synthetic OHLCV data paths
    with an added jump component. Parameters for both are estimated from historical data.
    """
    def __init__(self, historical_data: pd.DataFrame):
        if not all(col in historical_data.columns for col in ['open', 'high', 'low', 'close', 'volume']):
            raise ValueError("Historical data must contain OHLCV columns.")
        self.hist_data = historical_data
        self.hist_returns = historical_data['close'].pct_change().dropna()
        self.fitted_garch_model = None
        self.mean_drift = self.hist_returns.mean() # Mean drift from historical returns

        # Scaling factor for GARCH model fitting
        self.garch_scale_factor = 1000.0 # Recommended by arch warning

        # Initialize jump parameters to defaults, will be estimated later
        self.jump_intensity_lambda = 0.001 # Default small value
        self.jump_mean = 0.0
        self.jump_std = 0.001 # Default small value

        self._learn_historical_patterns() # Learn OHLC ratios and volume distribution
        self.fit_garch_model() # Fit GARCH model
        self._estimate_jump_parameters() # Estimate jump parameters from GARCH residuals

    def _learn_historical_patterns(self):
        """Analyzes historical data to learn distributions for OHLC and Volume."""
        self.hist_open_to_prev_close_ratio = (self.hist_data['open'] / self.hist_data['close'].shift(1)).dropna()
        self.hist_high_to_close_ratio = (self.hist_data['high'] / self.hist_data['close']).dropna()
        self.hist_low_to_close_ratio = (self.hist_data['low'] / self.hist_data['close']).dropna()
        self.hist_volume = self.hist_data['volume'].dropna()

    def fit_garch_model(self, p=1, q=1, dist='t'):
        """Fits a GARCH(p, q) model to the historical returns (diffusion component)."""
        logger.info(f"Fitting GARCH(p={p}, q={q}) model with '{dist}' distribution for diffusion component...")
        if self.hist_returns.empty:
            logger.warning("Historical returns series is empty. Cannot fit GARCH model.")
            self.fitted_garch_model = None
            return
        
        if self.hist_returns.std() < 1e-9:
            logger.warning("Historical returns have zero variance. GARCH model cannot be fitted. Simulating with constant returns.")
            self.fitted_garch_model = None
            return

        scaled_returns = self.hist_returns * self.garch_scale_factor
        
        garch_model = arch_model(scaled_returns, p=p, q=q, vol='Garch', dist=dist, rescale=False)
        try:
            self.fitted_garch_model = garch_model.fit(disp='off')
            logger.info("GARCH model fitting complete.")
        except Exception as e:
            logger.warning(f"GARCH model fitting failed: {e}. Simulating returns with historical mean and std dev.")
            self.fitted_garch_model = None

    def _estimate_jump_parameters(self, jump_threshold_std_dev: float = 3.0):
        """
        Estimates jump intensity, mean, and standard deviation from GARCH standardized residuals.
        """
        if self.fitted_garch_model is None:
            logger.warning("GARCH model not fitted. Cannot estimate jump parameters from residuals. Using default jump parameters.")
            return

        standardized_residuals = self.fitted_garch_model.resid / self.fitted_garch_model.conditional_volatility
        
        jumps = standardized_residuals[np.abs(standardized_residuals) > jump_threshold_std_dev]

        if not jumps.empty:
            self.jump_intensity_lambda = len(jumps) / len(self.hist_returns)
            actual_jumps_returns = self.hist_returns.loc[jumps.index]
            
            self.jump_mean = actual_jumps_returns.mean()
            self.jump_std = actual_jumps_returns.std()
            
            logger.info(f"Estimated Jump Parameters: Lambda={self.jump_intensity_lambda:.4f}, Mean={self.jump_mean:.4f}, Std={self.jump_std:.4f}")
        else:
            logger.info("No significant jumps detected in GARCH residuals. Using default (or very small) jump parameters.")
            self.jump_intensity_lambda = 0.001
            self.jump_mean = 0.0
            self.jump_std = 0.001


    def simulate_one_path(self, num_periods: int, start_date: pd.Timestamp, freq) -> Optional[pd.DataFrame]:
        """
        Generates a single, full synthetic OHLCV data path
        incorporating GARCH-modeled diffusion and a jump component.
        """
        if self.fitted_garch_model is None:
            logger.warning("GARCH model not fitted (possibly due to constant returns or fitting failure). Simulating returns with historical mean and std dev without GARCH dynamics.")
            sim_returns_base = np.random.normal(self.mean_drift, self.hist_returns.std(), num_periods)
        else:
            last_variance_scaled = self.fitted_garch_model.conditional_volatility.iloc[-1]**2
            last_variance = last_variance_scaled / (self.garch_scale_factor**2)
            
            params = self.fitted_garch_model.params
            omega_scaled = params['omega']
            alpha = params['alpha[1]']
            beta = params['beta[1]']
            nu = params.get('nu', np.inf)

            omega = omega_scaled / (self.garch_scale_factor**2)

            sim_returns_base = np.zeros(num_periods)
            current_variance = last_variance

            for t in range(num_periods):
                if self.fitted_garch_model.model.distribution.name == 'StudentsT':
                    random_shock_diffusion = np.random.standard_t(df=nu) * np.sqrt((nu - 2) / nu)
                else:
                    random_shock_diffusion = np.random.normal()
                
                diffusion_return = self.mean_drift + random_shock_diffusion * np.sqrt(current_variance)
                sim_returns_base[t] = diffusion_return
                
                current_variance = omega + alpha * (diffusion_return**2) + beta * current_variance
        
        num_jumps_per_period = np.random.poisson(self.jump_intensity_lambda, num_periods)
        jump_returns = np.zeros(num_periods)
        for t in range(num_periods):
            if num_jumps_per_period[t] > 0:
                jump_sizes = np.random.normal(self.jump_mean, self.jump_std, num_jumps_per_period[t])
                jump_returns[t] = np.sum(jump_sizes)
        
        sim_returns = sim_returns_base + jump_returns

        sim_close_prices = self.hist_data['close'].iloc[-1] * (1 + sim_returns).cumprod()

        synthetic_df = pd.DataFrame(index=pd.date_range(start=start_date, periods=num_periods, freq=freq))
        synthetic_df['close'] = sim_close_prices
        
        synthetic_df['open'] = np.nan
        synthetic_df['high'] = np.nan
        synthetic_df['low'] = np.nan
        synthetic_df['volume'] = np.nan
        
        if self.hist_open_to_prev_close_ratio.empty or self.hist_high_to_close_ratio.empty or self.hist_low_to_close_ratio.empty:
            logger.warning("Historical OHLC ratios are empty. Cannot accurately simulate OHLC. Returning None.")
            return None

        synthetic_df.loc[synthetic_df.index[0], 'open'] = self.hist_data['close'].iloc[-1] * np.random.choice(self.hist_open_to_prev_close_ratio)
        
        for i in range(1, num_periods):
            synthetic_df.loc[synthetic_df.index[i], 'open'] = synthetic_df['close'].iloc[i-1] * np.random.choice(self.hist_open_to_prev_close_ratio)

        synthetic_df['high'] = synthetic_df['close'] * np.random.choice(self.hist_high_to_close_ratio, size=num_periods)
        synthetic_df['low'] = synthetic_df['close'] * np.random.choice(self.hist_low_to_close_ratio, size=num_periods)

        synthetic_df['high'] = synthetic_df[['high', 'open', 'close']].max(axis=1)
        synthetic_df['low'] = synthetic_df[['low', 'open', 'close']].min(axis=1)
        
        synthetic_df['volume'] = np.random.choice(self.hist_volume, size=num_periods)
        
        return synthetic_df[['open', 'high', 'low', 'close', 'volume']]


class MonteCarloAnalyzer:
    """Handles analysis, plotting, and saving of Monte Carlo results."""
    def __init__(self, metrics_df: pd.DataFrame, all_equity_curves: list, deterministic_results: dict, output_dir: Path, all_simulated_paths: List[pd.DataFrame]):
        self.metrics_df = metrics_df
        self.all_equity_curves = all_equity_curves
        self.deterministic_results = deterministic_results
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.all_simulated_paths = all_simulated_paths
        sns.set_style("darkgrid")

    def save_summary_stats(self):
        """Calculates and saves descriptive statistics of performance metrics."""
        # Ensure these KPI names match the output from BacktestSimulator's _calculate_summary_metrics
        kpis = [
            'total_trades', 'total_profit_trades', 'total_loss_trades', 'win_rate',
            'gross_profit', 'gross_loss', 'net_profit', 'total_fees', 'profit_factor',
            'avg_profit_per_trade', 'avg_loss_per_trade', 'max_drawdown', 'sharpe_ratio',
            'sortino_ratio', 'initial_capital', 'final_capital', 'return_on_capital_pct'
        ]
        
        summary_stats = pd.DataFrame(index=['mean', 'std', 'min', '25%', '50%', '75%', 'max'])
        for kpi in kpis:
            if kpi in self.metrics_df.columns:
                # Convert to numeric, coercing errors to NaN, then drop NaNs for stats
                numeric_col = pd.to_numeric(self.metrics_df[kpi], errors='coerce').dropna()
                if not numeric_col.empty:
                    summary_stats[kpi] = numeric_col.describe(percentiles=[.25, .5, .75]).loc[['mean', 'std', 'min', '25%', '50%', '75%', 'max']]
                else:
                    summary_stats[kpi] = np.nan
            else:
                summary_stats[kpi] = np.nan
        
        filepath = self.output_dir / "1_performance_summary_stats.csv"
        summary_stats.to_csv(filepath)
        logger.info(f"Performance summary stats saved to {filepath}")
        logger.info("\n" + summary_stats.to_string(float_format="%.2f"))

        raw_filepath = self.output_dir / "all_simulation_metrics.csv"
        self.metrics_df.to_csv(raw_filepath, index=False)
        logger.info(f"Raw metrics for all simulations saved to {raw_filepath}")

    def plot_performance_distribution(self, metric='return_on_capital_pct'): # Changed default metric
        """Plots the distribution of a key performance metric."""
        plot_data = pd.to_numeric(self.metrics_df[metric], errors='coerce').dropna()

        if plot_data.empty:
            logger.warning(f"Metric '{metric}' not available or contains no valid numeric data for plotting.")
            return

        plt.figure(figsize=(12, 7))
        sns.histplot(plot_data, kde=True, bins=30, stat="density")
        
        det_metric = self.deterministic_results['metrics'].get(metric)
        # Ensure det_metric is numeric before plotting
        if pd.notna(det_metric) and isinstance(det_metric, (int, float)):
            plt.axvline(det_metric, color='red', linestyle='--', linewidth=2, label=f'Deterministic Result ({det_metric:.2f}%)')
        
        plt.title(f'Distribution of {metric.replace("_", " ").title()}', fontsize=16)
        plt.xlabel(metric.replace("_", " ").title())
        plt.ylabel('Density')
        plt.legend()
        plt.tight_layout()
        
        filepath = self.output_dir / f"2_distribution_{metric}.png"
        plt.savefig(filepath, dpi=300)
        plt.close()
        logger.info(f"Distribution plot for '{metric}' saved to {filepath}")

    def plot_equity_curves(self, num_to_plot=50):
        """Plots a sample of simulated equity curves against the deterministic baseline."""
        plt.figure(figsize=(15, 8))
        
        if self.all_equity_curves:
            non_empty_equity_curves = [curve for curve in self.all_equity_curves if not curve.empty]
            if non_empty_equity_curves:
                sample_size = min(num_to_plot, len(non_empty_equity_curves))
                indices_to_plot = np.random.choice(len(non_empty_equity_curves), sample_size, replace=False)
                for i in indices_to_plot:
                    equity_curve = non_empty_equity_curves[i]
                    if isinstance(equity_curve.index, pd.DatetimeIndex):
                        plt.plot(equity_curve.index, equity_curve, alpha=0.2, linewidth=1)
                    else:
                        logger.warning(f"Skipping plotting of a simulated equity curve due to non-DatetimeIndex. Index type: {type(equity_curve.index)}")
            else:
                logger.warning("No non-empty simulated equity curves to plot.")


        det_equity = self.deterministic_results.get('equity_curve')
        if det_equity is not None and not det_equity.empty:
            if isinstance(det_equity.index, pd.DatetimeIndex):
                plt.plot(det_equity.index, det_equity, color='red', linewidth=2.5, label='Deterministic Backtest')
            else:
                logger.warning(f"Skipping plotting deterministic equity curve due to non-DatetimeIndex. Index type: {type(det_equity.index)}")
        else:
            logger.warning("Deterministic equity curve is empty or not available for plotting.")
        
        plt.title('Simulated Equity Curves vs. Deterministic Backtest', fontsize=16)
        plt.xlabel('Date')
        plt.ylabel('Equity')
        plt.legend()
        plt.tight_layout()
        
        filepath = self.output_dir / "3_equity_curves_comparison.png"
        plt.savefig(filepath, dpi=300)
        plt.close()
        logger.info(f"Equity curve comparison plot saved to {filepath}")

    def plot_risk_reward_scatter(self, x_metric='max_drawdown', y_metric='return_on_capital_pct'): # Changed default metrics
        """Creates a scatter plot to visualize the risk/reward profile."""
        x_data = pd.to_numeric(self.metrics_df[x_metric], errors='coerce')
        y_data = pd.to_numeric(self.metrics_df[y_metric], errors='coerce')
        
        plot_df = pd.DataFrame({x_metric: x_data, y_metric: y_data}).dropna()

        if plot_df.empty:
            logger.warning(f"Cannot create scatter plot; no valid numeric data for {x_metric} or {y_metric}.")
            return
            
        plt.figure(figsize=(10, 8))
        sns.scatterplot(data=plot_df, x=x_metric, y=y_data, alpha=0.6)
        
        det_x = self.deterministic_results['metrics'].get(x_metric)
        det_y = self.deterministic_results['metrics'].get(y_metric)
        # Ensure det_x and det_y are numeric before plotting
        if pd.notna(det_x) and pd.notna(det_y) and isinstance(det_x, (int, float)) and isinstance(det_y, (int, float)):
            plt.scatter(det_x, det_y, color='red', s=150, marker='*', label='Deterministic Result', zorder=5)

        plt.title('Risk vs. Reward Profile (Each point is one simulation)', fontsize=16)
        plt.xlabel(x_metric.replace("_", " ").title())
        plt.ylabel(y_metric.replace("_", " ").title())
        plt.grid(True)
        plt.legend()
        plt.tight_layout()
        
        filepath = self.output_dir / "4_risk_reward_scatter.png"
        plt.savefig(filepath, dpi=300)
        plt.close()
        logger.info(f"Risk/reward scatter plot saved to {filepath}")

    def plot_simulated_ohlcv_paths(self, num_to_plot=5):
        """
        Plots a sample of simulated OHLCV paths (close prices) for visual inspection.
        """
        if not self.all_simulated_paths:
            logger.warning("No simulated OHLCV paths available to plot.")
            return

        plt.figure(figsize=(15, 8))
        
        non_empty_paths = [path for path in self.all_simulated_paths if not path.empty]

        if not non_empty_paths:
            logger.warning("All simulated OHLCV paths are empty. Skipping plot.")
            plt.close()
            return

        sample_size = min(num_to_plot, len(non_empty_paths))
        indices_to_plot = np.random.choice(len(non_empty_paths), sample_size, replace=False)

        for i in indices_to_plot:
            simulated_path = non_empty_paths[i]
            if isinstance(simulated_path.index, pd.DatetimeIndex):
                plt.plot(simulated_path.index, simulated_path['close'], alpha=0.6, linewidth=1.5, label=f'Sim {i+1} Close')
            else:
                logger.warning(f"Skipping plotting of simulated OHLCV path {i+1} due to non-DatetimeIndex.")

        det_ohlcv = self.deterministic_results.get('ohlcv_data')
        if det_ohlcv is not None and not det_ohlcv.empty and 'close' in det_ohlcv.columns:
            if isinstance(det_ohlcv.index, pd.DatetimeIndex):
                plt.plot(det_ohlcv.index, det_ohlcv['close'], color='black', linewidth=2.0, linestyle='--', label='Actual Test Data Close')
            else:
                logger.warning(f"Skipping plotting actual test data OHLCV due to non-DatetimeIndex.")


        plt.title(f'Sample of Simulated OHLCV Paths (Close Price) vs. Actual Test Data\n{self.deterministic_results.get("config_symbol", "")} {self.deterministic_results.get("config_interval", "")}', fontsize=16)
        plt.xlabel('Date')
        plt.ylabel('Price')
        plt.legend()
        plt.grid(True)
        plt.tight_layout()
        
        filepath = self.output_dir / "5_simulated_ohlcv_paths.png"
        plt.savefig(filepath, dpi=300)
        plt.close()
        logger.info(f"Sample of simulated OHLCV paths plot saved to {filepath}")


    def run_full_analysis(self):
        """Runs all analysis and plotting steps."""
        logger.info("--- Starting Monte Carlo Results Analysis ---")
        self.save_summary_stats()
        self.plot_performance_distribution(metric='return_on_capital_pct') # Ensure this metric exists in results
        self.plot_equity_curves()
        self.plot_risk_reward_scatter(x_metric='max_drawdown', y_metric='return_on_capital_pct') # Ensure these metrics exist
        self.plot_simulated_ohlcv_paths()
        logger.info("--- Monte Carlo Results Analysis Complete ---")


def run_mc_backtest_pipeline(symbol: str, interval: str, model_key: str, backtest_mode: str, train_ratio: float, num_simulations: int):
    logger.info(f"\n--- Starting Monte Carlo Backtest Run ---")
    logger.info(f"Symbol: {symbol}, Interval: {interval}, Model: {model_key}, Mode: {backtest_mode}")
    logger.info(f"Simulations: {num_simulations}")

    # --- 1. Load and Split Data ---
    dm = DataManager()
    try:
        data = dm.load_data(symbol=symbol, interval=interval, data_type='processed')
        if data is None or data.empty:
            raise FileNotFoundError(f"Historical processed data not found for {symbol} {interval}.")
        
        if not isinstance(data.index, pd.DatetimeIndex):
            data.index = pd.to_datetime(data.index, utc=True)
        if data.index.freq is None:
            inferred_freq = pd.infer_freq(data.index)
            if inferred_freq:
                data.index.freq = inferred_freq
                logger.info(f"Inferred data frequency: {inferred_freq}")
            else:
                logger.warning("Could not infer data frequency. Using 'min' as a fallback. This might cause issues with date_range generation.")
                # Defaulting to 'min' might still be problematic for larger intervals.
                # Consider adding logic to map common interval strings ('1h', '1d') to pandas offset aliases.
                data.index.freq = 'min' # This is a weak fallback. For robustness, need actual freq.


        if backtest_mode == 'full':
            train_data, test_data = data, data
        else:
            train_size = int(len(data) * train_ratio)
            train_data = data.iloc[:train_size]
            test_data = data.iloc[train_size:]
        
        num_periods = len(test_data)
        logger.info(f"Data split: {len(train_data)} train bars, {len(test_data)} test bars.")
        if num_periods == 0:
            raise ValueError("Test data set is empty. Adjust train_ratio or data size.")

    except Exception as e:
        logger.critical(f"Data loading/splitting failed: {e}", exc_info=True)
        sys.exit(1)

    # --- 2. Run Deterministic Backtest for Baseline ---
    logger.info("--- Running Deterministic Backtest for Baseline ---")
    deterministic_results = {}
    try:
        # FIX: Directly pass app_config.model, using 'model_config' keyword argument
        trainer = ModelTrainer(model_config=app_config.model) 
        trainer.load(symbol=symbol, interval=interval, model_key=model_key)
        
        model_feature_cols = trainer.feature_columns_original
        if not model_feature_cols:
            logger.warning("Original feature columns not found in loaded model metadata. Using features_to_use from config as fallback.")
            model_feature_cols = app_config.model.features_to_use # Use from app_config
            if not model_feature_cols:
                raise RuntimeError("Could not determine original feature columns used by the model.")

        initial_test_data_len = len(test_data)
        test_data_cleaned = test_data.dropna(subset=model_feature_cols).copy()
        rows_removed_cleaning = initial_test_data_len - len(test_data_cleaned)
        if rows_removed_cleaning > 0:
            logger.info(f"Removed {rows_removed_cleaning} rows from deterministic test_data due to NaNs in model feature columns.")
        
        if test_data_cleaned.empty:
            logger.warning("Deterministic test data is empty after cleaning NaNs. Skipping deterministic backtest.")
            # Set up a default empty result structure that MonteCarloAnalyzer can handle
            deterministic_results = {
                'trades': pd.DataFrame(),
                'equity_curve': pd.Series(dtype=float),
                'metrics': {
                    'total_trades': 0, 'net_profit': 0.0, 'return_on_capital_pct': 0.0,
                    'max_drawdown': 0.0, 'win_rate': 0.0, 'profit_factor': 0.0,
                    'sharpe_ratio': 0.0, 'sortino_ratio': 0.0, 'final_capital': app_config.strategy.initial_capital
                },
                'ohlcv_data': pd.DataFrame(),
                'config_symbol': symbol,
                'config_interval': interval
            }
        else:
            predictions = trainer.predict(test_data_cleaned).reindex(test_data_cleaned.index).fillna(0).astype(int)
            probabilities = trainer.predict_proba(test_data_cleaned).reindex(test_data_cleaned.index)

            det_backtest_simulator = BacktestSimulator( # Renamed variable
                data=test_data_cleaned.copy(),
                model_predict=predictions, model_proba=probabilities,
                symbol=symbol, interval=interval, model_type=model_key,
                # Config objects now accessed internally by BacktestSimulator from app_config
            )
            det_trades, det_equity, det_metrics = det_backtest_simulator.run_backtest()
            deterministic_results = {
                'trades': det_trades,
                'equity_curve': det_equity,
                'metrics': det_metrics,
                'ohlcv_data': test_data_cleaned.copy(),
                'config_symbol': symbol, # Pass config details for analyzer
                'config_interval': interval
            }
            logger.info("Deterministic backtest complete. Relevant data stored for analysis.")
    except Exception as e:
        logger.critical(f"Deterministic backtest failed, cannot proceed: {e}", exc_info=True)
        sys.exit(1)

    # --- 3. Initialize PricePathSimulator (GARCH + Jumps) ---
    if train_data.empty or len(train_data) < 2:
        logger.critical("Train data is too short or empty for PricePathSimulator. Exiting.")
        sys.exit(1)

    simulator = PricePathSimulator(train_data)
    
    logger.info(f"PricePathSimulator initialized for GARCH + Jumps simulation.")


    # --- 4. Run Simulation Loop ---
    all_metrics, all_equity_curves, all_simulated_paths = [], [], []
    logger.info("--- Starting Monte Carlo Simulation Loop ---")
    
    # Updated metric_keys_template to match BacktestSimulator._calculate_summary_metrics output
    # These keys are now directly populated by BacktestSimulator
    metric_keys_template = [
        'initial_capital', 'final_capital', 'net_profit', 'return_on_capital_pct',
        'max_drawdown', 'total_trades', 'win_rate', 'profit_factor', 'sharpe_ratio',
        'sortino_ratio', 'total_profit_trades', 'total_loss_trades', 'gross_profit',
        'gross_loss', 'avg_profit_per_trade', 'avg_loss_per_trade', 'avg_pnl_per_trade',
        'edge_expected_value', 'total_fees', 'avg_holding_duration_bars', 'equity_pnl_discrepancy'
        # Also include config_* keys for traceability
    ]
    
    # Re-use the trainer instance loaded for the deterministic backtest
    
    for i in tqdm(range(num_simulations), desc="Running Backtest Simulations"):
        sim_summary_metrics = {k: np.nan for k in metric_keys_template} # Initialize with NaN
        sim_equity_curve = pd.Series(dtype=float)

        try:
            # The freq inferred earlier might be weak, ensure it's compatible
            # For robustness, consider parsing interval string to a specific timedelta here for freq.
            sim_freq = test_data.index.freq # Use the inferred frequency from test_data
            if sim_freq is None:
                # Fallback if freq could not be inferred. Try to derive from interval string.
                # Example: '1h' -> 'H', '1d' -> 'D'
                # This is a simplification; a more robust solution would be needed.
                # For this context, assuming simple direct mapping or a standard default.
                if 'm' in interval:
                    sim_freq = f"{int(interval.replace('m',''))}min"
                elif 'h' in interval:
                    sim_freq = f"{int(interval.replace('h',''))}H"
                elif 'd' in interval:
                    sim_freq = f"{int(interval.replace('d',''))}D"
                else:
                    sim_freq = 'H' # Default to hourly if cannot parse
                logger.warning(f"Could not infer exact frequency for simulation. Using '{sim_freq}' as fallback.")

            synthetic_df = simulator.simulate_one_path(num_periods, start_date=test_data.index[0], freq=sim_freq)
            if synthetic_df is None or synthetic_df.empty:
                logger.warning(f"Simulation {i+1}: Generated empty synthetic data. Skipping.")
                sim_summary_metrics['error'] = 'Empty synthetic data'
                all_metrics.append(sim_summary_metrics)
                all_equity_curves.append(sim_equity_curve)
                all_simulated_paths.append(pd.DataFrame())
                continue
            
            all_simulated_paths.append(synthetic_df.copy())

            # Use app_config.features for the FeaturesEngineer
            feature_engineer = FeaturesEngineer(config=app_config.features) # Pass the FeatureConfig object
            featured_df = feature_engineer.process(synthetic_df)
            
            model_feature_cols = trainer.feature_columns_original
            if not model_feature_cols:
                logger.warning("Original feature columns not found in loaded model metadata for simulation. Using features_to_use from config as fallback.")
                model_feature_cols = app_config.model.features_to_use
                if not model_feature_cols:
                    raise RuntimeError("Could not determine original feature columns used by the model for simulation.")

            featured_df_cleaned = featured_df.dropna(subset=model_feature_cols).copy()
            if featured_df_cleaned.empty:
                logger.warning(f"Simulation {i+1}: Featured data is empty after cleaning NaNs. Skipping.")
                sim_summary_metrics['error'] = 'Empty featured data after cleaning'
                all_metrics.append(sim_summary_metrics)
                all_equity_curves.append(sim_equity_curve)
                continue

            sim_predictions = trainer.predict(featured_df_cleaned).reindex(featured_df_cleaned.index).fillna(0).astype(int)
            sim_probabilities = trainer.predict_proba(featured_df_cleaned).reindex(featured_df_cleaned.index)

            # Initialize BacktestSimulator with app_config components
            sim_backtest_simulator = BacktestSimulator( # Renamed variable
                data=featured_df_cleaned.copy(),
                model_predict=sim_predictions, model_proba=sim_probabilities,
                symbol=symbol, interval=interval, model_type=f"{model_key}_mc_sim",
                # Config objects now accessed internally by BacktestSimulator from app_config
            )
            # Disable saving intermediate backtest results for MC simulations to avoid clutter
            sim_backtest_simulator.save_trades = False
            sim_backtest_simulator.save_equity_curve = False
            sim_backtest_simulator.save_metrics = False
            
            _, sim_equity_curve, temp_summary_metrics = sim_backtest_simulator.run_backtest()
            
            # Update the initialized sim_summary_metrics with the results from the simulator
            sim_summary_metrics.update(temp_summary_metrics)

            all_metrics.append(sim_summary_metrics)
            all_equity_curves.append(sim_equity_curve)
        except Exception as e:
            logger.error(f"Backtest on simulation {i+1} failed: {e}", exc_info=False)
            sim_summary_metrics['error'] = str(e)
            all_metrics.append(sim_summary_metrics)
            all_equity_curves.append(sim_equity_curve)
            all_simulated_paths.append(pd.DataFrame())

    # --- 5. Aggregate and Analyze Results ---
    if not all_metrics:
        logger.error("No simulations were successfully completed. Exiting.")
        return

    # Convert list of dicts to DataFrame, ensuring all keys from template are present
    final_metrics_df = pd.DataFrame(all_metrics)
    # Reorder columns to match template, fill missing with NaN
    final_metrics_df = final_metrics_df.reindex(columns=metric_keys_template, fill_value=np.nan)

    # Create a unique output directory for this MC run
    run_output_timestamp = datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')
    mc_output_dir_name = f"{symbol.replace('/', '_')}_{interval}_{model_key}_mc_garch_jumps_{run_output_timestamp}"
    base_analysis_dir = Path(PATHS.get("backtesting_analysis_dir"))
    output_dir = base_analysis_dir / model_key / mc_output_dir_name
    output_dir.mkdir(parents=True, exist_ok=True)


    analyzer = MonteCarloAnalyzer(final_metrics_df, all_equity_curves, deterministic_results, output_dir, all_simulated_paths)
    analyzer.run_full_analysis()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Run advanced Monte Carlo backtests on a trained model.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter # Show defaults in help
    )
    parser.add_argument('--symbol', type=str, required=True, help='Trading pair symbol (e.g., BTCUSDT)')
    parser.add_argument('--interval', type=str, required=True, choices=['1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h', '12h', '1d', '3d', '1w', '1M'], help='Time interval (e.g., 1h, 1d)')
    parser.add_argument(
        '--model',
        type=str,
        required=True,
        choices=list(app_config.model.AVAILABLE_MODEL_TYPES.keys()),
        help='Model key from app_config.model.AVAILABLE_MODEL_TYPES'
    )
    parser.add_argument(
        '--backtest_mode',
        type=str,
        default=app_config.backtest.backtest_mode, # Get default from app_config.backtest
        choices=['full', 'train', 'test'],
        help='Data split to use for GARCH fitting and simulation length.'
    )
    parser.add_argument(
        '--train_ratio',
        type=float,
        default=app_config.model.train_test_split_ratio, # Get default from app_config.model
        help='Train/test split ratio for historical data.'
    )
    parser.add_argument(
        '--num_simulations',
        type=int,
        default=app_config.backtest.monte_carlo_n_simulations, # Get default from app_config.backtest
        help='Number of Monte Carlo simulations to run.'
    )
    
    args = parser.parse_args()

    try:
        run_mc_backtest_pipeline(
            symbol=args.symbol.upper(),
            interval=args.interval,
            model_key=args.model,
            backtest_mode=args.backtest_mode,
            train_ratio=args.train_ratio,
            num_simulations=args.num_simulations
        )
    except Exception as e:
        logger.critical(f"Unhandled exception in pipeline: {e}", exc_info=True)
    finally:
        logging.shutdown()
